server:
  port: 83
spring:
  datasource:
    url: jdbc:mysql://34.70.169.71:3306/fsdDevApp
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

